export enum CSSClass {
  authorization = 'authorization',
  authorizationTitle = 'authorization__title',
  authorizationInput = 'authorization__input',
  authorizationInputEmail = 'authorization__input-email',
  authorizationInputPassword = 'authorization__input-password',
  authorizationButton = 'authorization__button',
  authorizationSVG = 'authorization-svg',
  authorizationLogo = 'authorization__logo',
  header = 'header',
  headerShift = 'header-shift',
  headerWrapper = 'header-wrapper',
  headerLogo = 'header__logo',
  headerSVG = 'header-svg',
  headerBurger = 'header__burger',
  headerAuthorization = 'header__authorization',
  main = 'main',
  mainWrapper = 'main-wrapper',
  mainContainer = 'main-container',
  mainContainerShift = 'main-container-shift',
  mainPageTitle = 'main-page__title',
  mainPageText = 'main-page__text',
  mainPageBtn = 'main-page__btn',
  textbook = 'textbook',
  textbookWrapper = 'textbook-wrapper',
  textbookCard = 'textbook-card',
  textbookCardImage = 'textbook-card-image',
  textbookCardContent = 'textbook-card-content',
  textbookCardDelimeter = 'textbook-card-delimeter',
  textbookButtonsGroup = 'textbook-buttons-group',
  textbookMenuButtonWrapper = 'textbook-menu-button-wrapper',
  textbookMenuButton = 'textbook-menu-button',
  dimLight = 'dim-light',
  deleteBorder = 'delete-border',
  fillGray = 'fill-gray',
  gamesPage = 'games-page',
  gamesPageGame = 'games-page__game',
  gameAudio = 'game-audio',
  gameAudioGame = 'game-audio__game',
  gameAudioPreview = 'game-audio__preview',
  gameAudioAnswer = 'game-audio__answer',
  gameAudioAnswerNum = 'game-audio__answer_num',
  gameAudioAnswers = 'game-audio__answers',
  gameAudioHeader = 'game-audio__header',
  gameAudioHeaderBottom = 'game-audio__header-bottom',
  gameAudioHeaderImg = 'game-audio__header-img',
  gameAudioButton = 'game-audio__button',
  gameAudioButtonVoice = 'game-audio__button-voice',
  gameAudioButtonVoiceImg = 'game-audio__button-voice__img',
  gameAudioBlockButtons = 'game-audio__block-buttons',
  gameAudioBlockButtonsStart = 'game-audio__block-buttons__start',
  gameAudioBlockButtonsSelect = 'game-audio__block-buttons__select',
  gameAudioBlockButtonsFieldset = 'game-audio__block-buttons__fieldset',
  gameAudioBlockButtonsFieldsetBlock = 'game-audio__block-buttons__fieldset-block',
  gameAudioTitle = 'game-audio__title',
  gameAudioDescription = 'game-audio__description',
  gameAudioDescriptionBlock = 'game-audio__description-block',
  gameAudioDescriptionControl = 'game-audio__description-control',
  gamesPageGameName = 'games-page__game-name',
  gameAudioWrapperButton = 'game-audio__wrapper-button',
  gameAudioResultBlock = 'game-audio__result-block',
  gameAudioResultButtons = 'game-audio__result-buttons',
  lineThrough = 'line-through',
  rightAnswer = 'right-answer',
  warning = 'warning',
  warningMessage = 'warning-message',
  footer = 'footer',
  footerWrapper = 'footer-wrapper',
  footerYear = 'footer__year',
  footerRSSchool = 'footer__rsschool',
  footerLink = 'link',
  footerGithub = 'footer__github',
  closeBurger = 'close-burger',
  navItems = 'nav-items',
  navItem = 'nav-item',
  navItemIcon = 'item__icon',
  navItemName = 'item__name',
  aboutProjectTitle = 'about-project__title',
  aboutProjectText = 'about-project__text',
  aboutProjectAdvancedItems = 'about-project__advanced-items',
  aboutProjectAdvancedItem = 'about-project__advanced-item',
  aboutProjectAdvancedSvg = 'about-project__advanced-item__svg',
  aboutProjectAdvancedName = 'about-project__advanced-item__name',
  aboutProjectAdvancedText = 'about-project__advanced-item__text',
  aboutProjectBtnWrapper = 'about-project__btn-wrapper',
  aboutProjectBtn = 'about-project__btn',
  aboutProjectBtnYoutube = 'youtube',
  resultBlock = 'result-block',
  resultBlockTitle = 'result-block__title',
  resultBlockAnswer = 'result-block__answer',
  resultBlockRightAnswers = 'result-block__right-answers',
  resultBlockWrongAnswers = 'result-block__wrong-answers',
  resultBlockEnglishWord = 'result-block__english-word',
  resultBlockVoice = 'result-block__voice',
  title = 'title',
}

export enum AuthorizationText {
  mistakeUser = 'Пользователь с таким email не найден!',
  invalidEmail = 'Некорректный email!',
  incorrectPassword = 'Неверный пароль!',
  shortPassword = 'Пароль должен быть не менее 8 символов!',
  existsEmail = 'Такой email уже зарегистрирован',
}

export enum AudioGameText {
  name = 'аудиовызов',
  description = '«Аудиовызов» - это тренировка, которая улучшает восприятие речи на слух.',
  descriptionControlMouse = 'Используйте мышь, чтобы выбрать.',
  descriptionControlKey = 'Используйте цифровые клавиши от 1 до 5 для выбора ответа',
  descriptionControlReplayingVoice = 'Используйте пробел для повторного звучания слова',
  descriptionControlHint = 'Используйте клавишу Enter для подсказки или для перехода к следующему слову',
  startButton = 'Начать',
}

export enum HTMLPageFreeText {
  headerLogo = 'RSlang',
  footerYear = '2022',
  urlToRSSchool = 'https://rs.school/js/',
}

export enum MainPageText {
  mainPageTitle = 'RSLang',
  mainPageText = `Используй быстрый и эффективный способ
  изучения английского языка.<br> Все самые лучшие методики в одном месте.`,
  mainPageTextForUser = 'Hello ',
}

export enum FooterGithubUser {
  nameMax = 'maxlmysim',
  urlToGitHubeMax = 'https://github.com/maxlmysim',
  nameAnatoli = 'AnatoliHaralchuk',
  urlToGitHubeAnatoli = 'https://github.com/AnatoliHaralchuk',
  nameIlya = 'Naysa3r',
  urlToGitHubeIlya = 'https://github.com/naysa3r',
}

export enum AboutPtojectText {
  title = 'О ПРОЕКТЕ',
  text = `Приложение для изучения иностранных слов с техникой интервального повторения,
  отслеживания индивидуального прогресса и мини-игр.`,
  ebookText = `Возможность изучать слова разного уровня,<br>
  отмечать сложные и подучать новые знания`,
  dictionaryText = `Возможность изучения неизвестных,<br>
  или труднозапоминаемых по другой схеме`,
  gameText = `Игры позволяют провести время не только в удовольствие,
  но и с пользой`,
  statisticsText = `Можно легко оценивать свой
  уровень знаний по статистике`,
  aboutProjectBtn = 'Назад',
  aboutProjectYoutube = 'Видео',
  youtubeFrame = `<iframe width="560" height="315"
  src="https://www.youtube.com/embed/-WR5EEl5YyE"
  title="YouTube video player" frameborder="0" allow="accelerometer; autoplay;
  clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen></iframe>`,
}
